### ISSUE TITLE
isSelectable 는 불필요해보이는데 필요한 건가요?(잘 몰라서)

### ISSUE THREAD

**Issue by bestheroz** [mabaji/todoList#1]
https://github.com/mabaji/todoList/blob/fa57fb77623a9d5d04a863e6733b7a0300749419/todo-list/src/views/Game.vue#L191

**Comment by mabaji** [comment]
> https://github.com/mabaji/todoList/blob/fa57fb77623a9d5d04a863e6733b7a0300749419/todo-list/src/views/Game.vue#L191

게임이 시작되면 선택완료 버튼이 기다리는중입니다로 변경되는 기능이에요~ ^^ (게임시작 버튼 클릭 여부)

**Comment by bestheroz** [comment]
myChoice값으로는 같이 쓸수 없을까요?
myChoice  값에 따라 isSelectable 가 종속적이어서 굳이 필요없지 않을까 해서요.

3,2,1, 동안 가려지는 기능도 있는 거네요.
